# Generated by Django 3.0.2 on 2020-05-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertenant',
            old_name='delete',
            new_name='create_permission',
        ),
        migrations.RenameField(
            model_name='usertenant',
            old_name='read',
            new_name='delete_permission',
        ),
        migrations.RenameField(
            model_name='usertenant',
            old_name='update',
            new_name='read_permission',
        ),
        migrations.AddField(
            model_name='usertenant',
            name='update_permission',
            field=models.BooleanField(default=False),
        ),
    ]
